### ISSUE TITLE
No plugins imported

### ISSUE THREAD

**Issue by PriscillaRolvers** [fcskit/obsidian-eln#4]
Would you mind sharing the community and core plugins used in the vault? They aren't imported as I open the folder as vault. There is no warning to activate the plugins as well.

**Comment by fcskit** [comment]
You probably opened the folder the zip-archive was unpacked to as a vault. This will not work. The actual vault folder is called ELN_vault. I updated the "Getting started" section of the README accordingly. I hope it is clearer now. If you want to find out which plugins are installed, you have to locate the .obsidian folder (ELN_vault/.obsidian). Depending on your operating system this folder may be hidden, so you need to activate "show hidden files" in your file manager. In the .obsidian folder you will find a folder called plugins, which contains a folder for each installed plugin.
